version: 2

updates:
  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      day: monday
      time: "08:27"
      timezone: America/New_York
    open-pull-requests-limit: 10
    groups:
      rust-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:37"
      timezone: America/New_York
    open-pull-requests-limit: 10
    groups:
      actions-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: ci
